POST {{url}}/shop/signup
Content-Type: application/json
x-api-key: {{apiKey}}

{
    "name": "shop7",
    "email": "shop7@gmai.com",
    "password": "123!@#"
}


###
# @name loginRequest
POST {{url}}/shop/login
Content-Type: application/json
x-api-key: {{apiKey}}

{
    "email": "shop7@gmai.com",
    "password": "123!@#"
}


###
POST {{url}}/shop/logout
Content-Type: application/json
x-api-key: {{apiKey}}
x-client-id: {{clientId}}
Authorization: {{accessToken}}


###
POST {{url}}/shop/refresh-token
Content-Type: application/json
x-api-key: {{apiKey}} 
x-client-id: {{clientId}}
x-refresh-token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2NTU0N2NiZGI5YmVjYzMxNDk4Y2YwZjEiLCJlbWFpbCI6InNob3A3QGdtYWkuY29tIiwiaWF0IjoxNzAwNTY3OTUxLCJleHAiOjE3MDExNzI3NTF9.VJxRt4d-6Zi8KjWyCT-hhX09l07yf58dbJZqvrerg5s