

POST {{url}}/checkout/review
Content-Type: application/json
x-api-key: {{apiKey}} 
x-client-id: {{clientId}}
Authorization: {{accessToken}} 

{
    "cartId": "6560b30a9967fb1da96dab4d",
    "userId": 1000,
    "shop_order_ids" : 
    [
        {
            "shopId": "65547cbdb9becc31498cf0f1",
            "shop_discounts" : [],
            "item_products": [
                {
                    "productId": "655bf9d535cec304d34690b8",
                    "quantity": 2
                },
                {
                    "productId": "655f4867ed60da1929ce4faa",
                    "quantity": 2
                }
            ]
        }
    ]
}