
POST {{url}}/product
Content-Type: application/json
x-api-key: {{apiKey}} 
x-client-id: {{clientId}}
Authorization: {{accessToken}} 

{
    "product_name": "Dung cu tap the hinh (ta binh voi)",
    "product_description": "Dung cu tap the hinh, nang cao chat luong cuoc song",
    "product_price" : 100000,
    "product_type": "Clothing",
    "product_thumb": "product_thumb",
    "product_quantity": 5,
    "product_attribute" : {
        "brand": "FPT Sport",
        "size": "L",
        "material": "sat"
    }
}

###

PATCH {{url}}/product/655bf9d535cec304d34690b8
Content-Type: application/json
x-api-key: {{apiKey}} 
x-client-id: {{clientId}}
Authorization: {{accessToken}} 

{
    "product_name": "New Jeans 02",
    "product_description": "High quality denim jeans updated",
    "product_type": "Clothing",
    "product_attribute" : {
        "size": "XXL",
        "material": "denim golden"
    }
}


###

POST {{url}}/product/publish/655f4867ed60da1929ce4faa
Content-Type: application/json
x-api-key: {{apiKey}} 
x-client-id: {{clientId}}
Authorization: {{accessToken}} 


###
GET {{url}}/product/drafts/all
Content-Type: application/json
x-api-key: {{apiKey}} 
x-client-id: {{clientId}}
Authorization: {{accessToken}} 


###
GET {{url}}/product/published/all
Content-Type: application/json
x-api-key: {{apiKey}} 
x-client-id: {{clientId}}
Authorization: {{accessToken}} 


###

GET {{url}}/product/search/micro
x-api-key: {{apiKey}}


###
# @name getAllProducts
GET {{url}}/product
x-api-key: {{apiKey}}